repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.2.0
      hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
          exclude: "docs"

    - repo: https://github.com/timothycrosley/isort
      rev: 5.10.1
      hooks:
        - id: isort
          exclude: "docs"

    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
        - id: black
          exclude: "docs"

    - repo: https://github.com/pycqa/flake8
      rev: ''
      hooks:
        - id: flake8
          types:
            - python
          exclude: "docs"

    - repo: https://github.com/pycqa/pydocstyle
      rev: 6.1.1
      hooks:
        - id: pydocstyle

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v0.942'
      hooks:
      -   id: mypy
          files: sqlalchemy_heavyai/
