name: sqla-omnisci
channels:
  - conda-forge
dependencies:
  - sqlalchemy
  - pyomnisci>=0.27.0
  - pyomniscidb>=5.5.2
  # dev
  - black
  - flake8
  - jupyterlab
  - sphinx
  - mypy
  - pip
  - pydocstyle
  - pre-commit
  - pytest
  - sphinx
  - toml
  - twine
  - pip:
    # docs
    - jupyter-book
    - sphinx-autoapi
    - sphinx-external-toc
    - sphinx-jupyterbook-latex
