name: sqla-heavyai
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.8
  - sqlalchemy <2
  - heavyai
  # dev
  - pre-commit
  - pytest
  # docs
  - sphinx
  - jupyter-book
  - sphinx-autoapi
  - sphinx-external-toc
  - sphinx-jupyterbook-latex
