name: sqla-omnisci
channels:
  - conda-forge
dependencies:
  - sqlalchemy
  - pyomnisci>=0.27.0
  - pyomniscidb>=5.5.2
  # dev
  - black
  - pip
  - flake8
  - sphinx
  - twine
  - pytest
  - pre-commit
  - pydocstyle
