version: '3.9'
services:

  heavydb:
    image: heavyai/core-os-cpu
    hostname: heavydb
    ports:
      - 6274:6274
      - 6278:6278
    volumes:
      - ./heavydb.conf:/var/lib/heavyai/heavy.conf:ro

  superset:
    # docs: https://hub.docker.com/r/apache/superset
    build:
      context: .
      dockerfile: Dockerfile.superset
    hostname: superset
    ports:
      # - 8088:8088  # used for superset >1.2
      - 8080:8080  # used for supserset =1.1
      - 5000:5000  # for testing
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ..:/opt/sqlalchemy-heavyai
    command: |
      flask run -p 8080 --with-threads --reload --debugger --host=0.0.0.0

  waiter:
    image: jwilder/dockerize
    command: |
      dockerize -wait tcp://heavydb:6274
        -wait-retry-interval 5s
        -timeout 1m
