name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Install flit
        run: pip install flit

      - name: Build
        run: flit build

      - name: Publish to PyPI
        env:
          FLIT_USERNAME: __token__
          FLIT_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          flit publish

      - name: Create a GitHub Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: ${{ github.event.release.tag_name }}
          name: Release ${{ github.event.release.tag_name }}
          commit: main
          body: Release ${{ github.event.release.tag_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
